### ISSUE TITLE
Doesn't work if you install kms at different directory.

### ISSUE THREAD

**Issue by normankee552** [NexerqDev/Verdant#3]
Install my kms at my c drive and it doesn't detect, but it detect when install to d drive

**Comment by nicholastay** [comment]
Not sure why this would be the case.

Verdant simply launches NGM with authentication data, and it's all hands off from there. Perhaps check out #1 for some registry values you could change to update the game path to your D drive version.

**Comment by normankee552** [comment]
I mean I install it on C drive since my D drive is load of Work. Is there any way to change so they will load from c drive?

**Comment by nicholastay** [comment]
If you've installed it properly through the installer, NGM should have updated this change with itself.

Verdant does not know where your game is installed. It only talks to NGM. So you need to make sure NGM is aware of where your current game directory is.
